#!/usr/bin/env python3
"""
regen_kw.py — Re-generate KW từ "Điều giải thích từ ngữ" cho 1 luật đã có.
Đọc data/luat_NNN.js → extract KW + re-link → write back.

Usage:
  python3 regen_kw.py luat_122_2025
"""
import re, sys, json
from pathlib import Path

REPO = Path('/Users/nguyentanphong/Desktop/WEB - CÁC ĐƠN VỊ/Website-c-nh-n')
DATA_DIR = REPO / 'legalmap' / 'data'

if len(sys.argv) < 2:
    print("Usage: python3 regen_kw.py luat_122_2025")
    sys.exit(1)

law_id = sys.argv[1]
js_path = DATA_DIR / f"{law_id}.js"
if not js_path.exists():
    print(f"❌ Không tìm thấy: {js_path}")
    sys.exit(1)

# Run node để extract data structure
import subprocess
node_script = f'''
global.window = {{}};
require('{js_path}');
const r = window.LUAT_REGISTRY['{law_id}'];
console.log(JSON.stringify({{
  meta: r.meta,
  CH: r.CH,
  DD: r.DD,
  KW_old: r.KW
}}));
'''
out = subprocess.run(['node', '-e', node_script], capture_output=True, text=True)
if out.returncode != 0:
    print("❌ Node parse failed:", out.stderr)
    sys.exit(1)

data = json.loads(out.stdout.strip())
meta = data['meta']
CH = data['CH']
DD = data['DD']
KW_old = data['KW_old']

# Find Điều giải thích từ ngữ
gt = next((d for d in DD if re.search(r'giải thích từ ngữ|định nghĩa', d.get('name',''), re.IGNORECASE)), None)
if not gt:
    print(f"❌ Không tìm thấy Điều 'Giải thích từ ngữ' trong {law_id}")
    sys.exit(1)

print(f"📄 {law_id} — {meta['title']}")
print(f"   Điều giải thích: Đ.{gt['n']} ({gt['name']})")
print(f"   KW cũ: {len(KW_old)}")

# Extract KW từ definitions
full = gt['full']
items = re.split(r'\n(?=\d+\.\s+[A-ZẮÂÊÔƠƯĐÁÀẢÃẠÂẦẤẨẪẬĂẰẮẲẴẶÉÈẺẼẸÊỀẾỂỄỆÍÌỈĨỊÓÒỎÕỌÔỒỐỔỖỘƠỜỚỞỠỢÚÙỦŨỤƯỪỨỬỮỰÝỲỶỸỴ])', full)

KW_new = []
used_ids = set()
for it in items:
    m = re.match(r'^\d+\.\s+([^\n]+?)\s+là\s+([^\n]+)', it.strip())
    if not m:
        continue
    term = m.group(1).strip()

    # Generate id
    words = re.sub(r'[^\w\sÀ-ỹ]', '', term).split()
    if len(words) >= 2:
        kid = 'k' + ''.join(w[0].upper() for w in words[:3])
    else:
        kid = 'k' + term[:3].upper().replace(' ', '')
    base = kid; i = 2
    while kid in used_ids:
        kid = base + str(i); i += 1
    used_ids.add(kid)

    # Label
    if len(term) > 14:
        mid = len(term) // 2
        sp = term.find(' ', mid - 3)
        lbl = (term[:sp] + '\\n' + term[sp+1:]) if sp > 0 else term
    else:
        lbl = term

    kw_type = 'kwc' if len(words) <= 3 else 'kwg'

    KW_new.append({
        'id': kid,
        'lbl': lbl,
        'type': kw_type,
        'terms': [term.lower()],
    })

print(f"   KW mới (auto): {len(KW_new)}")

# Re-link DD with new KW
def find_kw(content, KW):
    matched = []
    cl = content.lower()
    for kw in KW:
        for term in kw['terms']:
            if term and term.lower() in cl:
                matched.append(kw['id'])
                break
    return matched

for d in DD:
    d['kw'] = find_kw(d['full'], KW_new)

print(f"   Total links điều→KW mới: {sum(len(d['kw']) for d in DD)}")
print(f"   Điều có 0 KW: {sum(1 for d in DD if not d['kw'])}")

# Generate JS file
out_lines = []
out_lines.append('// ═══════════════════════════════════════════════════')
out_lines.append(f"// DATA MODULE — {meta['title']} {meta['sohieu']}")
out_lines.append('// LegalMap · Hướng Dương Edition')
out_lines.append('// KW regenerated by regen_kw.py từ Điều "Giải thích từ ngữ"')
out_lines.append('// ═══════════════════════════════════════════════════')
out_lines.append('')
out_lines.append('window.LUAT_REGISTRY = window.LUAT_REGISTRY || {};')
out_lines.append(f"window.LUAT_REGISTRY['{law_id}'] = {{")
out_lines.append('')
out_lines.append('  meta: {')
for k, v in meta.items():
    if isinstance(v, str):
        out_lines.append(f"    {k}: '{v}',")
    else:
        out_lines.append(f"    {k}: {v},")
out_lines.append('  },')
out_lines.append('')

# CH
out_lines.append('CH:[')
for c in CH:
    lbl = c['lbl'].replace("\n","\\n").replace("'","\\'")
    desc = c['desc'].replace("\n","\\n").replace("'","\\'")
    out_lines.append(f"  {{id:'{c['id']}',lbl:'{lbl}',from:{c['from']},to:{c['to']},")
    out_lines.append(f"   desc:'{desc}'}},")
out_lines.append('],')
out_lines.append('')

# DD
out_lines.append('DD:[')
for a in DD:
    name = a['name'].replace("'","\\'")
    full_text = a['full'].replace("`","'")
    kw_str = ','.join(f"'{k}'" for k in a['kw'])
    out_lines.append(f"{{n:{a['n']},name:'{name}',kw:[{kw_str}],")
    out_lines.append(f"full:`{full_text}`}},")
    out_lines.append('')
out_lines.append('],')
out_lines.append('')

# KW
out_lines.append('KW:[')
for k in KW_new:
    lbl = k['lbl'].replace("'","\\'")
    terms = "','".join(t.replace("'","\\'") for t in k['terms'])
    out_lines.append(f"  {{id:'{k['id']}',  lbl:'{lbl}', type:'{k['type']}',")
    out_lines.append(f"   terms:['{terms}']}},")
out_lines.append('],')
out_lines.append('')
out_lines.append('NOKW_SET: new Set([]),')
out_lines.append('')
out_lines.append('};')

js_path.write_text('\n'.join(out_lines))
print(f"   ✅ Updated {js_path}")
